#!/usr/bin/env node
/**
 * SEO Data Generator for WallpaperVerse
 *
 * Reads wallpapers.json and generates:
 * 1. js/seo-data.js — Compact inline metadata map for instant meta tag injection
 * 2. Appends <noscript> internal links to index.html for crawl discovery
 *
 * Run: npm run build:seo (or: node scripts/generate-seo.js)
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const WALLPAPERS_JSON = path.join(ROOT, "wallpapers.json");
const SEO_DATA_OUTPUT = path.join(ROOT, "js", "seo-data.js");
const INDEX_HTML = path.join(ROOT, "index.html");

// Category display names
const categoryNames = {
  anime: "Anime",
  marvel: "Marvel",
  dc: "DC Universe",
  movies: "Movies & TV Shows",
  cars: "Car Culture",
  football: "Football",
  transformers: "Transformers",
  wanderlust: "Wanderlust",
  random: "Random",
};

function generateId(filename) {
  return filename
    .replace(/\.(jpg|jpeg|png|webp)$/i, "")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

function main() {
  console.log("🔧 Generating SEO data...\n");

  // Read wallpapers.json
  const data = JSON.parse(fs.readFileSync(WALLPAPERS_JSON, "utf-8"));

  // Build compact metadata map: id -> { t: title, c: category, d: description, i: image }
  const seoMap = {};
  const allLinks = []; // For noscript internal linking

  for (const [category, items] of Object.entries(data)) {
    const catName = categoryNames[category] || category;

    items.forEach((item) => {
      const id = generateId(item.file);
      const title = item.title;
      const desc = `Download ${title} wallpaper in 4K HD quality. Free ${catName} wallpaper for desktop, laptop & mobile. High-resolution download from WallpaperVerse.`;

      seoMap[id] = {
        t: title, // title
        c: catName, // category display name
        d: desc, // meta description
        i: item.optimized, // image path (optimized)
      };

      allLinks.push({ id, title, category: catName });
    });
  }

  // Generate js/seo-data.js
  const jsContent = `// Auto-generated by scripts/generate-seo.js — DO NOT EDIT
// Compact wallpaper metadata for instant SEO meta tag injection
window.__SEO_DATA__ = ${JSON.stringify(seoMap)};
`;

  fs.writeFileSync(SEO_DATA_OUTPUT, jsContent, "utf-8");
  console.log(`✅ Generated ${SEO_DATA_OUTPUT}`);
  console.log(`   ${Object.keys(seoMap).length} wallpapers indexed\n`);

  // Generate <noscript> internal links block for index.html
  const noscriptStart = "<!-- SEO:NOSCRIPT_LINKS_START -->";
  const noscriptEnd = "<!-- SEO:NOSCRIPT_LINKS_END -->";

  let linksHtml = `${noscriptStart}\n<noscript>\n<div style="padding:2rem;background:#0a0a0a;color:#ccc">\n<h2>All Wallpapers</h2>\n<ul>\n`;

  allLinks.forEach((link) => {
    linksHtml += `<li><a href="wallpaper?id=${link.id}">${link.title} - ${link.category} Wallpaper</a></li>\n`;
  });

  // Add category links
  for (const [catId, catName] of Object.entries(categoryNames)) {
    linksHtml += `<li><a href="collection?id=${catId}">${catName} Wallpapers Collection</a></li>\n`;
  }

  linksHtml += `</ul>\n</div>\n</noscript>\n${noscriptEnd}`;

  // Insert or replace in index.html
  let indexHtml = fs.readFileSync(INDEX_HTML, "utf-8");

  if (indexHtml.includes(noscriptStart)) {
    // Replace existing block
    const regex = new RegExp(`${noscriptStart}[\\s\\S]*?${noscriptEnd}`, "g");
    indexHtml = indexHtml.replace(regex, linksHtml);
  } else {
    // Insert before </body>
    indexHtml = indexHtml.replace("</body>", `${linksHtml}\n</body>`);
  }

  fs.writeFileSync(INDEX_HTML, indexHtml, "utf-8");
  console.log(
    `✅ Updated ${INDEX_HTML} with ${allLinks.length} noscript links\n`,
  );

  console.log("🚀 SEO data generation complete!");
}

main();
