#!/usr/bin/env node
/**
 * SEO Data Generator for WallpaperVerse
 *
 * Reads wallpapers.json and generates:
 * 1. js/seo-data.js — Compact inline metadata map for instant meta tag injection
 * 2. image-sitemap.xml — Dedicated image sitemap for Google Image Search
 * 3. Updates <noscript> internal links in index.html for crawl discovery
 *
 * Run: npm run build:seo (or: node scripts/generate-seo.js)
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const WALLPAPERS_JSON = path.join(ROOT, "wallpapers.json");
const SEO_DATA_OUTPUT = path.join(ROOT, "js", "seo-data.js");
const IMAGE_SITEMAP_OUTPUT = path.join(ROOT, "image-sitemap.xml");
const INDEX_HTML = path.join(ROOT, "index.html");
const BASE_URL = "https://wallpaperverse.akshthakkar.me";

// Category display names
const categoryNames = {
  anime: "Anime",
  marvel: "Marvel",
  dc: "DC Universe",
  movies: "Movies & TV Shows",
  cars: "Car Culture",
  football: "Football",
  transformers: "Transformers",
  wanderlust: "Wanderlust",
  random: "Random",
};

function generateId(filename) {
  return filename
    .replace(/\.(jpg|jpeg|png|webp)$/i, "")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

function escapeXml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function main() {
  console.log("🔧 Generating SEO data...\n");

  const data = JSON.parse(fs.readFileSync(WALLPAPERS_JSON, "utf-8"));
  const today = new Date().toISOString().split("T")[0];

  // Build data structures
  const seoMap = {};
  const allLinks = [];
  const imageEntries = []; // For image sitemap

  for (const [category, items] of Object.entries(data)) {
    const catName = categoryNames[category] || category;

    items.forEach((item) => {
      const id = generateId(item.file);
      const title = item.title;
      const desc = `Download ${title} wallpaper in 4K HD quality. Free ${catName} wallpaper for desktop, laptop & mobile. High-resolution download from WallpaperVerse.`;

      seoMap[id] = {
        t: title,
        c: catName,
        d: desc,
        i: item.optimized,
      };

      allLinks.push({ id, title, category: catName });

      // Image sitemap entry — use original (highest quality) image
      imageEntries.push({
        pageUrl: `${BASE_URL}/wallpaper?id=${id}`,
        imageUrl: `${BASE_URL}/${item.original}`,
        title: `${title} - ${catName} Wallpaper 4K HD`,
        caption: desc,
        license: "https://creativecommons.org/licenses/by-nc/4.0/",
      });
    });
  }

  // ==========================================
  // 1. Generate js/seo-data.js
  // ==========================================
  const jsContent = `// Auto-generated by scripts/generate-seo.js — DO NOT EDIT
// Compact wallpaper metadata for instant SEO meta tag injection
window.__SEO_DATA__ = ${JSON.stringify(seoMap)};
`;
  fs.writeFileSync(SEO_DATA_OUTPUT, jsContent, "utf-8");
  console.log(`✅ Generated ${SEO_DATA_OUTPUT}`);
  console.log(`   ${Object.keys(seoMap).length} wallpapers indexed\n`);

  // ==========================================
  // 2. Generate image-sitemap.xml
  // ==========================================
  let imageSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
`;

  imageEntries.forEach((entry) => {
    imageSitemap += `  <url>
    <loc>${escapeXml(entry.pageUrl)}</loc>
    <image:image>
      <image:loc>${escapeXml(entry.imageUrl)}</image:loc>
      <image:title>${escapeXml(entry.title)}</image:title>
      <image:caption>${escapeXml(entry.caption)}</image:caption>
      <image:license>${entry.license}</image:license>
    </image:image>
  </url>
`;
  });

  imageSitemap += `</urlset>\n`;

  fs.writeFileSync(IMAGE_SITEMAP_OUTPUT, imageSitemap, "utf-8");
  console.log(`✅ Generated ${IMAGE_SITEMAP_OUTPUT}`);
  console.log(`   ${imageEntries.length} image entries\n`);

  // ==========================================
  // 3. Update <noscript> internal links in index.html
  // ==========================================
  const noscriptStart = "<!-- SEO:NOSCRIPT_LINKS_START -->";
  const noscriptEnd = "<!-- SEO:NOSCRIPT_LINKS_END -->";

  let linksHtml = `${noscriptStart}\n<noscript>\n<div style="padding:2rem;background:#0a0a0a;color:#ccc">\n<h2>All Wallpapers</h2>\n<ul>\n`;

  allLinks.forEach((link) => {
    linksHtml += `<li><a href="wallpaper?id=${link.id}">${link.title} - ${link.category} Wallpaper</a></li>\n`;
  });

  for (const [catId, catName] of Object.entries(categoryNames)) {
    linksHtml += `<li><a href="collection?id=${catId}">${catName} Wallpapers Collection</a></li>\n`;
  }

  linksHtml += `</ul>\n</div>\n</noscript>\n${noscriptEnd}`;

  let indexHtml = fs.readFileSync(INDEX_HTML, "utf-8");

  if (indexHtml.includes(noscriptStart)) {
    const regex = new RegExp(`${noscriptStart}[\\s\\S]*?${noscriptEnd}`, "g");
    indexHtml = indexHtml.replace(regex, linksHtml);
  } else {
    indexHtml = indexHtml.replace("</body>", `${linksHtml}\n</body>`);
  }

  fs.writeFileSync(INDEX_HTML, indexHtml, "utf-8");
  console.log(
    `✅ Updated ${INDEX_HTML} with ${allLinks.length} noscript links\n`,
  );

  console.log("🚀 SEO data generation complete!");
}

main();
